### ISSUE TITLE
Incompatible with Anki 2.1.24 beta

### ISSUE THREAD

**Issue by ghost** [lovac42/ReMemorize#22]
Throws the following error when rescheduling using Ctrl+M. Latest [changes](https://betas.ankiweb.net/#/)
Debug info:
Anki 2.1.24 (9dda5cf6) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-21 19:23:18

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\323586997\rememorize.py", line 174, in ask
    tipTxt=self.evalDays(c,days)
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\323586997\rememorize.py", line 185, in evalDays
    cnt=self.reschedCards(c, days)
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\323586997\rememorize.py", line 112, in reschedCards
    customReschedCards(cids,days,days,log,fuzz)
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\323586997\utils.py", line 45, in customReschedCards
    mw.col.db.executemany("""
  File "lib\site-packages\anki\dbproxy.py", line 87, in executemany
AssertionError

**Comment by lovac42** [comment]
thx, should be fixed with latest commit.

**Comment by ghost** [comment]
Thank you very much!

**Comment by lovac42** [comment]
Something to note...

Anki's auto update check will disable this addon due to the max_point_version for this addon was set to -23 on ankiweb. It completely discards the packaging info and mod time in package.json during import. The data from the server overwrites the packaging info and disables this addon after restart. So you must manually edit the meta.json file and change it from -23 to 24 DAILY.

**Comment by ghost** [comment]
Got it. Thanks for the update.
